### ISSUE TITLE
 11:06:17.647] [FATAL] SYSTEM   - TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by tablecell** [restocat/restocat-example#1]
node -v
v7.7.0
npm -v
4.1.2
node server.js 

 [FATAL] SYSTEM   - TypeError: Promise.defer is not a function
    at Server.listen (restocat-example-master\node_modules\restocat\lib\Server.js:87:25)
    at Object.<anonymous> (restocat-example-master\server.js:29:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)

**Comment by chetverikov** [comment]
Thank you so much for finding this!
Unfortunately, I haven't updated this example. Will definitely do it soon.

**Comment by chetverikov** [comment]
Update example
